// projects/rawkode.academy/website/src/components/command-palette/index.tsx
import { Command } from "cmdk";
import {
	type ReactElement,
	useCallback,
	useEffect,
	useMemo,
	useRef,
	useState,
} from "react";
import { SkeletonList } from "@/components/common/SkeletonList";
import { getCategoryIcon, GitHubIcon } from "./icons";
import {
	type ColorScheme,
	getColorScheme,
	setColorScheme,
} from "@/lib/theme";
import "./styles.css";

interface NavigationItem {
	id: string;
	title: string;
	description?: string;
	href?: string;
	category: string;
	keywords?: string[];
	action?: () => boolean | void;
	scheme?: ColorScheme;
}

type CommandPage = "root" | "appearance";

interface CommandPaletteProps {
	isOpen: boolean;
	onClose: () => void;
}

// Track analytics events client-side
const trackEvent = (event: string, properties?: Record<string, unknown>) => {
	try {
		window.posthog?.capture(event, properties);
	} catch {
		// Ignore tracking errors
	}
};

export default function CommandPalette({
	isOpen,
	onClose,
}: CommandPaletteProps): ReactElement | null {
	const [search, setSearch] = useState("");
	const [navigationItems, setNavigationItems] = useState<NavigationItem[]>([]);
	const [articleItems, setArticleItems] = useState<NavigationItem[]>([]);
	const [isLoading, setIsLoading] = useState(false);
	const [isSearchingArticles, setIsSearchingArticles] = useState(false);
	const inputRef = useRef<HTMLInputElement>(null);
	const searchTimeoutRef = useRef<NodeJS.Timeout | null>(null);
	const [currentScheme, setCurrentScheme] = useState<ColorScheme>("light");
	const [pages, setPages] = useState<CommandPage[]>(["root"]);
	const [hasLoadedNavigation, setHasLoadedNavigation] = useState(false);
	const hasTrackedOpen = useRef(false);

	const activePage = pages[pages.length - 1];
	const isRootPage = activePage === "root";

	const goToPage = useCallback((page: CommandPage) => {
		setPages((prev) => [...prev, page]);
		setSearch("");
	}, []);

	const goBack = useCallback(() => {
		setPages((prev) => (prev.length > 1 ? prev.slice(0, -1) : prev));
		setSearch("");
	}, []);

	const customFilter = (value: string, search: string): number => {
		if (!search.trim()) return 1; // Show all items when search is empty

		const searchTerms = search.toLowerCase().split(/\s+/).filter(Boolean);
		const valueLower = value.toLowerCase();

		// Check if all search terms are found in the value
		return searchTerms.every((term) => valueLower.includes(term)) ? 1 : 0;
	};

	const appearanceItems = useMemo<NavigationItem[]>(
		() =>
			(["light", "dark"] as const).map((nextScheme) => ({
				id: `appearance-${nextScheme}`,
				title: nextScheme === "dark" ? "Dark mode" : "Light mode",
				description: `Switch to ${nextScheme} mode`,
				category: "Appearance",
				keywords: [
					"theme",
					"appearance",
					"color",
					"mode",
					nextScheme,
					nextScheme === "dark" ? "night" : "day",
				],
				scheme: nextScheme,
				action: () => {
					const previous = currentScheme;
					setColorScheme(nextScheme);
					setCurrentScheme(nextScheme);
					trackEvent("color_scheme_switched", {
						from_scheme: previous,
						to_scheme: nextScheme,
						source: "command_palette",
					});
				},
			})),
		[currentScheme],
	);

	const commandItems = useMemo(
		() => [
			{
				id: "command-change-appearance",
				title: "Change appearance",
				description: "Switch between light and dark mode",
				category: "Commands",
				keywords: ["theme", "appearance", "color", "mode", "dark", "light"],
				action: () => {
					goToPage("appearance");
					return false;
				},
			},
		],
		[goToPage],
	);

	useEffect(() => {
		// Get current color scheme
		setCurrentScheme(getColorScheme());

		const handleSchemeChange = (event: Event) => {
			const customEvent = event as CustomEvent<{ scheme: ColorScheme }>;
			setCurrentScheme(customEvent.detail.scheme);
		};
		window.addEventListener("color-scheme-change", handleSchemeChange);

		return () => {
			if (typeof window !== "undefined") {
				window.removeEventListener("color-scheme-change", handleSchemeChange);
			}
		};
	}, []);

	useEffect(() => {
		if (!isOpen || hasLoadedNavigation) return;

		const abortController = new AbortController();

		const fetchNavigationItems = async () => {
			setIsLoading(true);

			try {
				const response = await fetch("/api/sitemap-pages.json", {
					signal: abortController.signal,
				});

				if (!response.ok) {
					return;
				}

				const sitemapItems: NavigationItem[] = await response.json();
				setNavigationItems(
					sitemapItems.filter((item) => item.category !== "Articles"),
				);
				setHasLoadedNavigation(true);
			} catch (error) {
				if (error instanceof DOMException && error.name === "AbortError") {
					return;
				}
			} finally {
				if (!abortController.signal.aborted) {
					setIsLoading(false);
				}
			}
		};

		fetchNavigationItems();

		return () => {
			abortController.abort();
		};
	}, [hasLoadedNavigation, isOpen]);

	// Search for articles when user types
	useEffect(() => {
		if (searchTimeoutRef.current) {
			clearTimeout(searchTimeoutRef.current);
		}

		if (!isOpen || activePage !== "root") {
			setArticleItems([]);
			setIsSearchingArticles(false);
			return;
		}

		if (search.length >= 2) {
			const abortController = new AbortController();

			setIsSearchingArticles(true);
			searchTimeoutRef.current = setTimeout(async () => {
				try {
					const response = await fetch(
						`/api/search-articles.json?q=${encodeURIComponent(search)}`,
						{ signal: abortController.signal },
					);
					if (response.ok) {
						const articles: NavigationItem[] = await response.json();
						setArticleItems(articles);
					}
				} catch (error) {
					if (error instanceof DOMException && error.name === "AbortError") {
						return;
					}
				} finally {
					if (!abortController.signal.aborted) {
						setIsSearchingArticles(false);
					}
				}
			}, 300); // Debounce search

			return () => {
				abortController.abort();
				if (searchTimeoutRef.current) {
					clearTimeout(searchTimeoutRef.current);
				}
			};
		} else {
			setArticleItems([]);
			setIsSearchingArticles(false);
		}

		return () => {
			if (searchTimeoutRef.current) {
				clearTimeout(searchTimeoutRef.current);
			}
		};
	}, [activePage, isOpen, search]);

	useEffect(() => {
		const handleKeyDown = (e: KeyboardEvent) => {
			if (e.key === "Escape") {
				onClose();
			}
		};

		if (isOpen) {
			document.addEventListener("keydown", handleKeyDown);
			document.body.style.overflow = "hidden";
			// Focus the input after the component has rendered
			setTimeout(() => {
				inputRef.current?.focus();
			}, 0);
		}

		return () => {
			document.removeEventListener("keydown", handleKeyDown);
			document.body.style.overflow = "unset";
		};
	}, [isOpen, onClose]);

	useEffect(() => {
		if (!isOpen) {
			setPages(["root"]);
			setSearch("");
			hasTrackedOpen.current = false;
		} else if (!hasTrackedOpen.current) {
			// Track command palette opened
			trackEvent("command_palette_opened", {
				trigger: "keyboard_shortcut",
			});
			hasTrackedOpen.current = true;
		}
	}, [isOpen]);

	const handleSelect = (item: NavigationItem) => {
		// Track navigation event
		trackEvent("command_palette_navigation", {
			item_id: item.id,
			item_title: item.title,
			category: item.category,
			is_external: item.href?.startsWith("http") ?? false,
			has_action: !!item.action,
			search_query: search || undefined,
		});

		if (item.action) {
			const shouldClose = item.action();
			if (shouldClose !== false) {
				onClose();
			}
			return;
		}

		if (!item.href) return;

		if (item.href.startsWith("http")) {
			window.open(item.href, "_blank");
		} else {
			// Ensure absolute path navigation
			const absolutePath = item.href.startsWith("/")
				? item.href
				: `/${item.href}`;
			window.location.assign(absolutePath);
		}
		onClose();
	};

	const getItemIcon = (item: NavigationItem) => {
		if (item.href) {
			try {
				const url = new URL(item.href, window.location.origin);
				if (
					url.hostname === "github.com" ||
					url.hostname === "www.github.com"
				) {
					return GitHubIcon;
				}
			} catch {
				// Invalid URL or relative path, fall through to default
			}
		}
		return getCategoryIcon(item.category);
	};

	if (!isOpen) return null;

	const rootItems = [...commandItems, ...navigationItems, ...articleItems];
	const appearancePageItems = [
		{
			id: "command-back-to-root",
			title: "Back to commands",
			description: "Return to the main menu",
			category: "Commands",
			keywords: ["back", "commands", "appearance", "return"],
			action: () => {
				goBack();
				return false;
			},
		},
		...appearanceItems,
	];

	const displayedItems =
		activePage === "appearance" ? appearancePageItems : rootItems;

	const groupedItems = displayedItems.reduce(
		(acc, item) => {
			if (!acc[item.category]) {
				acc[item.category] = [];
			}
			acc[item.category]?.push(item);
			return acc;
		},
		{} as Record<string, NavigationItem[]>,
	);

	return (
		<div className="command-palette-overlay" onClick={onClose}>
			<div
				className="command-palette-container"
				onClick={(e) => e.stopPropagation()}
			>
				<Command className="command-palette" filter={customFilter}>
					<div className="command-palette-header">
						<div
							style={{
								position: "relative",
								width: "100%",
								display: "flex",
								alignItems: "center",
							}}
						>
							<svg
								className="command-palette-search-icon"
								fill="none"
								stroke="currentColor"
								viewBox="0 0 24 24"
								style={{
									position: "absolute",
									left: "16px",
									top: "50%",
									transform: "translateY(-50%)",
									zIndex: 1,
									pointerEvents: "none",
								}}
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									strokeWidth={2}
									d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
								/>
							</svg>
							<Command.Input
								ref={inputRef}
								placeholder={
									activePage === "appearance"
										? "Search appearance..."
										: "Search pages..."
								}
								value={search}
								onValueChange={setSearch}
								className="command-palette-input"
								style={{
									paddingLeft: "52px",
									paddingRight: "70px",
									width: "100%",
								}}
							/>
							<kbd
								className="command-palette-kbd"
								style={{
									position: "absolute",
									right: "16px",
									top: "50%",
									transform: "translateY(-50%)",
									zIndex: 1,
								}}
							>
								ESC
							</kbd>
						</div>
					</div>

					<Command.List className="command-palette-list">
						{isLoading && (
							<div className="command-palette-loading">
								<SkeletonList
									items={5}
									showIcon={true}
									iconSize="1.5rem"
									showSubtitle={false}
									className="command-palette-skeleton"
								/>
							</div>
						)}

						{isRootPage &&
							isSearchingArticles &&
							!isLoading &&
							search.length >= 2 && (
								<div className="command-palette-searching">
									<SkeletonList
										items={3}
										showIcon={true}
										iconSize="1.5rem"
										showSubtitle={true}
										className="command-palette-skeleton"
									/>
								</div>
							)}

						<Command.Empty className="command-palette-empty">
							{!isLoading &&
								!isSearchingArticles &&
								(activePage === "appearance"
									? `No appearance options match "${search}"`
									: `No results found for "${search}"`)}
						</Command.Empty>

						{Object.entries(groupedItems).map(([category, items]) => {
							const CategoryIcon = getCategoryIcon(category);
							return (
								<Command.Group
									key={category}
									heading={
										<div className="flex items-center gap-2">
											<CategoryIcon className="command-palette-category-icon" />
											{category}
										</div>
									}
									className="command-palette-group"
								>
									{items.map((item) => {
										const ItemIcon = getItemIcon(item);
										const isActiveScheme = item.scheme === currentScheme;
										return (
											<Command.Item
												key={item.id}
												value={`${item.title} ${item.description || ""} ${item.keywords?.join(" ") || ""}`}
												onSelect={() => handleSelect(item)}
												className="command-palette-item"
											>
												<ItemIcon className="command-palette-item-icon" />
												<div className="command-palette-item-content">
													<div className="command-palette-item-title">
														{item.title}
														{isActiveScheme && (
															<span className="ml-2 text-xs text-primary">
																(active)
															</span>
														)}
													</div>
												</div>
												{item.href && item.href.startsWith("http") && (
													<svg
														className="command-palette-external-icon"
														fill="none"
														stroke="currentColor"
														viewBox="0 0 24 24"
													>
														<path
															strokeLinecap="round"
															strokeLinejoin="round"
															strokeWidth={2}
															d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
														/>
													</svg>
												)}
											</Command.Item>
										);
									})}
								</Command.Group>
							);
						})}
					</Command.List>
				</Command>
			</div>
		</div>
	);
}

// projects/rawkode.academy/website/src/components/command-palette/CommandPalette.vue
<script setup lang="ts">
import { Combobox, createListCollection } from "@ark-ui/vue/combobox";
import { Dialog } from "@ark-ui/vue/dialog";
import { academyCommand, academyLayout, dialog } from "@rawkodeacademy/design-system";
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { getColorSchemePreference, setColorScheme, type ColorSchemePreference } from "@/lib/theme";

interface Item {
	id: string;
	title: string;
	description?: string;
	href?: string;
	category: string;
	keywords?: string[];
	preference?: ColorSchemePreference;
}
interface SearchResult extends Omit<Item, "category"> { type: string }
const props = defineProps<{ returnFocus: () => HTMLElement | null }>();
function trackEvent(event: string, properties?: Record<string, unknown>) {
	try { window.posthog?.capture(event, properties); } catch { /* Analytics must not interrupt navigation. */ }
}
const s = academyCommand();
const layout = academyLayout();
const modal = dialog({ tone: "academy" });
let returnFocus = props.returnFocus();
const open = ref(true);
const query = ref("");
const appearance = ref(false);
const navigation = ref<Item[]>([]);
const results = ref<Item[]>([]);
const navigationLoaded = ref(false);
const loadingNavigation = ref(false);
const searching = ref(false);
const navigationError = ref(false);
const searchError = ref(false);
const preference = ref<ColorSchemePreference>("system");
const inputContainer = ref<HTMLElement | null>(null);
const categoryFor: Record<string, string> = { video: "Videos", article: "Articles", news: "News", course: "Learning", "learning-path": "Learning", show: "Shows", technology: "Technology" };
const appearanceItems: Item[] = [
	{ id: "back", title: "Back to commands", category: "Commands" },
	{ id: "light", title: "Light mode", description: "Always use the light theme", category: "Appearance", preference: "light" },
	{ id: "dark", title: "Dark mode", description: "Always use the dark theme", category: "Appearance", preference: "dark" },
	{ id: "system", title: "System theme", description: "Follow your operating system preference", category: "Appearance", preference: "system" },
];
const items = computed(() => {
	const remoteHrefs = new Set(results.value.map(item => item.href));
	const candidates: Item[] = appearance.value ? appearanceItems : [
		{ id: "appearance", title: "Change appearance", description: "Choose light, dark, or system theme", category: "Commands", keywords: ["theme", "mode"] },
		...navigation.value.filter(item => !remoteHrefs.has(item.href)),
	];
	const terms = query.value.toLowerCase().trim().split(/\s+/).filter(Boolean);
	const local = candidates.filter(item => terms.every(term => `${item.title} ${item.description ?? ""} ${item.keywords?.join(" ") ?? ""}`.toLowerCase().includes(term)));
	// The server ranks content matches. Do not filter those a second time by title.
	return appearance.value ? local : [...local, ...results.value];
});
const groups = computed(() => [...new Set(items.value.map(item => item.category))].map(category => ({ category, items: items.value.filter(item => item.category === category) })));
const collection = computed(() => createListCollection({ items: items.value, itemToString: item => item.title, itemToValue: item => item.id }));

watch(open, async (isOpen, _previous, onCleanup) => {
	if (!isOpen) { query.value = ""; appearance.value = false; return; }
	trackEvent("command_palette_opened");
	preference.value = getColorSchemePreference();
	if (navigationLoaded.value) return;
	const controller = new AbortController();
	onCleanup(() => controller.abort());
	loadingNavigation.value = true;
	navigationError.value = false;
	try {
		const response = await fetch("/api/sitemap-pages.json", { signal: controller.signal });
		if (!response.ok) throw new Error("Navigation unavailable");
		const data: Item[] = await response.json();
		if (controller.signal.aborted) return;
		navigation.value = data.filter(item => item.category !== "Articles").map(item => ({ ...item, id: `page:${item.id}` }));
		navigationLoaded.value = true;
	} catch { if (!controller.signal.aborted) navigationError.value = true; }
	finally { if (!controller.signal.aborted) loadingNavigation.value = false; }
}, { immediate: true });

watch([query, appearance, open], ([value, isAppearance, isOpen], _old, onCleanup) => {
	results.value = [];
	searching.value = false;
	searchError.value = false;
	if (!isOpen || isAppearance || value.trim().length < 2) return;
	const controller = new AbortController();
	searching.value = true;
	const timer = setTimeout(async () => {
		try {
			const response = await fetch(`/api/search.json?q=${encodeURIComponent(value)}`, { signal: controller.signal });
			if (!response.ok) throw new Error("Search unavailable");
			const data: SearchResult[] = await response.json();
			if (controller.signal.aborted) return;
			results.value = data.map(item => ({ ...item, id: `result:${item.type}:${item.id}`, category: categoryFor[item.type] ?? "Pages" }));
		} catch { if (!controller.signal.aborted) searchError.value = true; }
		finally { if (!controller.signal.aborted) searching.value = false; }
	}, 300);
	onCleanup(() => { clearTimeout(timer); controller.abort(); });
});

function selectItem(id: string | undefined) {
	const item = items.value.find(item => item.id === id);
	if (!item) return;
	if (id === "appearance" || id === "back") { appearance.value = id === "appearance"; query.value = ""; return; }
	if (item.preference) {
		const previous = preference.value;
		setColorScheme(item.preference); preference.value = item.preference;
		trackEvent("color_scheme_switched", { from_preference: previous, to_preference: item.preference, source: "command_palette" });
	}
	else if (item.href) {
		trackEvent("command_palette_navigation", { item_id: item.id, item_title: item.title, category: item.category });
		const url = new URL(item.href, window.location.origin);
		if (!["http:", "https:"].includes(url.protocol)) return;
		if (url.origin === window.location.origin) window.location.assign(url.href);
		else window.open(url.href, "_blank", "noopener,noreferrer");
	}
	open.value = false;
}
function openPalette() {
	if (!open.value && document.activeElement instanceof HTMLElement) returnFocus = document.activeElement;
	open.value = true;
}
function onKeydown(event: KeyboardEvent) {
	if ((event.metaKey || event.ctrlKey) && ["k", "/"].includes(event.key.toLowerCase())) {
		event.preventDefault();
		if (open.value) open.value = false; else openPalette();
	}
}
onMounted(() => { document.addEventListener("open-command-palette", openPalette); document.addEventListener("keydown", onKeydown); });
onUnmounted(() => { document.removeEventListener("open-command-palette", openPalette); document.removeEventListener("keydown", onKeydown); });
</script>

<template>
	<Dialog.Root v-model:open="open" :initial-focus-el="() => inputContainer?.querySelector('input') ?? null" :final-focus-el="() => returnFocus?.isConnected ? returnFocus : props.returnFocus()" :trap-focus="true" :prevent-scroll="true">
		<Teleport to="body">
			<Dialog.Backdrop :class="modal.backdrop" />
			<Dialog.Positioner :class="s.positioner">
				<Dialog.Content :class="s.content">
					<div :class="s.header">
						<Dialog.Title :class="s.title">{{ appearance ? 'Appearance' : 'Search and commands' }}</Dialog.Title>
						<Dialog.CloseTrigger :class="layout.buttonSecondary">Close</Dialog.CloseTrigger>
					</div>
					<div ref="inputContainer">
						<Combobox.Root :collection="collection" :open="true" :input-value="query" :model-value="[]" :loop-focus="true" :close-on-select="false" selection-behavior="preserve" @input-value-change="query = $event.inputValue" @value-change="selectItem($event.value[0])">
							<Combobox.Control>
								<Combobox.Input :class="s.input" aria-label="Search content and commands" placeholder="Search the Academy…" @keydown.esc.prevent="open = false" @keydown.backspace="!query && (appearance = false)" />
							</Combobox.Control>
							<Combobox.Content :class="s.list">
								<Combobox.ItemGroup v-for="group in groups" :key="group.category">
									<Combobox.ItemGroupLabel :class="s.group">{{ group.category }}</Combobox.ItemGroupLabel>
									<Combobox.Item v-for="item in group.items" :key="item.id" :item="item" :class="s.item">
										<Combobox.ItemText :class="s.label">{{ item.title }}{{ item.preference === preference ? ' (current)' : '' }}</Combobox.ItemText>
										<span v-if="item.description" :class="s.description">{{ item.description }}</span>
									</Combobox.Item>
								</Combobox.ItemGroup>
							</Combobox.Content>
						</Combobox.Root>
					</div>
					<p v-if="loadingNavigation || searching" :class="s.status" role="status">{{ searching ? 'Searching content…' : 'Loading navigation…' }}</p>
					<p v-else-if="!items.length" :class="s.status" role="status">No results. Try another search.</p>
					<p v-if="navigationError || searchError" :class="s.status" role="alert">{{ searchError ? 'Content search is unavailable.' : 'Navigation could not be loaded.' }} <a href="/search">Open the search page</a>.</p>
					<Dialog.Description :class="s.footer">Use arrow keys to browse, Enter to select, and Escape to close.</Dialog.Description>
				</Dialog.Content>
			</Dialog.Positioner>
		</Teleport>
	</Dialog.Root>
</template>
